# Generated by Django 4.2.13 on 2024-07-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txtDoc', models.TextField(blank=True, verbose_name='document')),
                ('strClasse', models.CharField(blank=True, max_length=100, verbose_name='classe')),
            ],
        ),
    ]
